name: 'Kubernetes toolset'
description: 'Github Action with Kubernetes tools: kubectl, kustomize, helm, kubeval, conftest, jq, yq, go'
author: 'Stefan Prodan'
branding:
  icon: 'command'
  color: 'blue'
inputs:
  command:
    description: 'command to run'
    required: true
  kubectl:
    description: 'kubectl version'
  kustomize:
    description: 'kustomize version'
  helm:
    description: 'helm version'
  helmv3:
    description: 'helm version'
runs:
  using: 'docker'
  image: 'docker://stefanprodan/kube-tools:v1.5.0'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.kubectl }}
    - ${{ inputs.kustomize }}
    - ${{ inputs.helm }}
    - ${{ inputs.helmv3 }}