name: 'Kubernetes toolset'
description: 'Github Action with Kubernetes tools: kubectl, kustomize, helm, kubeval, conftest, jq, yq, go'
author: 'Stefan Prodan'
branding:
  icon: 'command'
  color: 'blue'
inputs:
  command:
    description: 'command to run'
    required: true
  kubectl:
    description: 'kubectl version e.g. 1.16.0'
  kustomize:
    description: 'kustomize version e.g. 3.4.0'
  helm:
    description: 'helm version e.g. 2.16.1'
  helmv3:
    description: 'helm version e.g. 3.0.0'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.kubectl }}
    - ${{ inputs.kustomize }}
    - ${{ inputs.helm }}
