name: 'Kubernetes toolset'
description: 'Github Action with Kubernetes tools: kubectl, kustomize, helm, kubeval, kubeaudit, conftest, jq, yq, go'
author: 'Stefan Prodan'
branding:
  icon: 'command'
  color: 'blue'
inputs:
  command:
    description: 'command to run'
    required: true
  kubectl:
    description: 'kubectl version'
  kustomize:
    description: 'kustomize version'
  helm:
    description: 'helm version'
  helmv3:
    description: 'helm version'
  kubeseal:
    description: 'kubeseal version'
  kubeaudit:
    description: 'kubeaudit version'
  kubeval:
    description: 'kubeval version'
  conftest:
    description: 'conftest version'
  kubeconform:
    description: 'kubeconform version'
  yq:
    description: 'yq version'
  kyverno:
    description: 'kyverno version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.kubectl }}
    - ${{ inputs.kustomize }}
    - ${{ inputs.helm }}
    - ${{ inputs.helmv3 }}
    - ${{ inputs.kubeseal }}
    - ${{ inputs.kubeval }}
    - ${{ inputs.conftest }}
    - ${{ inputs.kubeconform }}
    - ${{ inputs.yq }}
    - ${{ inputs.kyverno }}
